apiVersion: v1
kind: ConfigMap
metadata:
  name: idenkey-application
data:
  application.properties: |
    server.port=8080
    spring.application.name = iDenkey
    eureka.client.serviceUrl.defaultZone  = http://toppan-sit.ddns.net:32266/eureka/
    eureka.client.healthcheck.enabled = false
    ##disable the spring security on the management endpoints like /env, /refresh etc.
    management.security.enabled = false
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details = ALWAYS
    spring.config.import=optional:configserver:
    test_mode = false
    test_mode_hint = ### Test Mode:
    #management.port = 9000
    ## Configuring info endpoint
    info.app.name=iDenkey4FIDO
    info.app.description=desc iDenkey4FIDO
    info.app.version=2.2.0
    config_file_path=${config_directory}/config.properties
    log4j_file_path=file:${config_directory}/log4j2.xml
    err_msg_path=${config_directory}
    Component-A=%TGB$RFV
    Component-B=%^TYGHBN
    Component-C=VFR$#edc
    spring.datasource.driver-class-name=com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
    spring.datasource.url=jdbc-secretsmanager:mysql://idenkey-instance-1.ckcctg5jmane.ap-east-1.rds.amazonaws.com:3306/idgfid
    spring.datasource.username=rds!cluster-053dd780-3ce3-4787-80bd-ff5b9d0d8b66
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    spring.jpa.properties.hibernate.dialect.storage_engine=innodb
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.properties.hibernate.default_schema=dbo
    # cache
    spring.jpa.properties.javax.persistence.sharedCache.mode=ENABLE_SELECTIVE
    spring.jpa.properties.hibernate.cache.use_second_level_cache=true
    spring.jpa.properties.hibernate.cache.use_query_cache=true
    spring.jpa.properties.hibernate.cache.region.factory_class=jcache
    spring.jpa.properties.hibernate.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
    spring.jpa.properties.hibernate.javax.cache.uri=ehcache.xml
    spring.jpa.properties.hibernate.generate_statistics=true
    logging.level.org.hibernate.SQL=DEBUG
    logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
    #spring.datasource.maximum-pool-size=100
    #spring.datasource.connection-timeout=300
    #spring.datasource.connection-test-query=Select 1
    #spring.datasource.max_wait=5000
    #spring.datasource.initial_size=10
    use_swagger = true
    # To disable API
    springdoc.api-docs.enabled=${use_swagger}
    springdoc.api-docs.path=/rp-docs
    springdoc.swagger-ui.operationsSorter=method
    #springdoc.swagger-ui.path=/swagger-ui-idgate.html
    #cron.expression = 0 0/1 * * * ?
    ## default:v1/public/uaf/facets
    app-ID=v1/public/uaf/facets
    ## default:5431#3280
    Allowed-Aaids=5431#3280
    ## For Trace
    #AllowedAaids=8888#6666
    ## default:300000
    server_data_timeout = 300000
  config.properties: |
    i18n_Name = Message
    OTP_Timeout = 300000
    Txn_Timeout = 300000
    LoginTxn_Timeout = 300000
    WSI_API_Key = API_Key
    WSM_API_Key = API_Key
    # FIDO server settings
    FIDO_SV_IP = http://192.168.0.116:10000/GW/WSM/
    # validation fail limits
    #Digital_Fail_Limit = 3
    #Pattern_Fail_Limit = 3
    ### ---------- iDenkey  -----------###
    # Look out for space at tail when you're setting this config
    ## 1 OnlyOTP = true (\u4E0D\u6AA2\u6838 step 4  \u5167\u7684 OTP and ...  ; default = false)
    ## 2 OnlyFIDO = true (\u4E0D\u6253 step 4  \u5167\u7684 FIDO ; default = false)
    # OnlyOTP = true
    #OnlyFIDO = true
    ##  default enableOTP = true
    # enableOTP = false
    mobilePubKey=3059301306072A8648CE3D020106082A8648CE3D0301070342000403C0A3D74A7BDFC6E8EB0BE90A821A82CB85714E9DEC74062D7E149A4E90D5526A16F52F8919FC99403C978367CEC38E788A7AB0F1E5B8936ED93D5CB01AF93C
    # DbKeyAlias=DbKeyAlias
    RsaKeyAlias=RSAKEYALIAS
    ECCkeyAlias=ECCkeyAlias
    SoftRSA = true
    SoftECC= true
    ## default: 300000
    #OTP_Timeout = 300000
    ##  default: 300000
    #Txn_Timeout = 300000
    # validation fail limits
    ##  default: 999
    Digital_Fail_Limit = 999
    Pattern_Fail_Limit = 999
    OTP_Fail_Limit = 12
    HSMPlusMode = Y
    HSMProvider = Cvn
    ## SafeNet
    HSM_SLOT=2
    HSM_PXD=1234
    PersoKeyAlias = CHBKEY123
    DbKeyAlias = CHBKEY123
    SetKeyAlias = CHBKEY123
    AlwaysCallHSM = N
    # --- ESCP --- #
    MultiPersoKey = N
    # Using Multi Perso Key
    PersoKeyBAlias = 02
    PersoKeyCAlias = 03
    EncryptUrl =
    DecryptUrl =
  secretsmanager.properties: |
    drivers.region = ap-east-1
  Message_en.properties: |
    00000 = Success
    M0001 = iDGateID not found
    M0002 = iDGateID status error
    M0003 = iDGateID locked
    M0004 = iDGateID deleted
    M0005 = iDGateID not match
    M0006 = FIDO Server connection error
    M0007 = FIDO Server error
    M0008 = Database error
    M0009 = Internal error
    M0010 = Input parameter error
    M0011 = POST to remote service failed
    M0012 = Return message error
    M0013 = Unknown method
    M0014 = JSON parse error
    M0015 = Channel invalid
    M0016 = Push Server error
    
    M0051 = Channel name doesn't match to the member
    M0052 = API key invalid
    
    M0060 = Locked for too many fail authentication
    
    M0100 = Cannot add an existing verifyType
    M0101 = Cannot replace a verifyType which is not present
    M0102 = Cannot replace all verifyTypes
    M0103 = Cannot create an idgate ID
    
    M0150 = QR Code is not available
    
    M0200 = VerifyType not match
    
    0000 = Success
    0001 = iDGateID not found
    0002 = iDGateID status error
    0003 = iDGateID locked
    0004 = iDGateID deleted
    0005 = iDGateID not match
    0006 = Trust Server connection error
    0007 = Trust Server error
    0008 = Database error
    0010 = Input parameter error
    0011 = POST to remote service failed
    0012 = Return message error
    0013 = Unknown method
    0014 = JSON parse error
    0015 = Channel invalid
    0018 = Failed to generate key
    0020 = OTP invalid
    0021 = Data decrypt failed
    0051 = Channel name doesn't match to the member
    0052 = API key invalid
    0057 = This request is timed out. Please refresh and try again.
    0058 = Data encryption failure
    0060 = Locked for too many fail authentication
    0070 = Illegal Argument
    0600 = Member channel invalid
    0601 = Data decrypt failed
    0602 = Failed to generate hash
    0603 = Message invalid
    0604 = Member hash invalid
    0605 = JSON parse error
    0606 = Request timeout
    0607 = OTP invalid
    0608 = Locked for too many fail authentication
    0609 = Cannot turn on an authentication type which is on already
    0610 = Blocked authentication type
    0611 = Cannot turn off an authentication type which is off already
    0612 = Data encryption failure
    0650 = Member channel invalid
    0651 = Data decrypt failed
    0652 = Failed to generate hash
    0653 = Message invalid
    0654 = Member hash invalid
    0655 = JSON parse error
    0656 = Not an active authentication type
    0657 = Unknown authentication type
    0658 = Request invalid
    0659 = Token invalid
    0660 = OTP invalid
    0661 = Locked for too many fail authentication
    0662 = Pattern key is the same as set currently
    0663 = Digital key is the same as set currently
    0664 = Data encryption failure
    0700 = Member channel invalid
    0701 = Data decrypt failed
    0702 = Failed to generate hash
    0703 = Message invalid
    0704 = Member hash invalid
    0705 = JSON parse error
    0706 = Request timeout
    0707 = OTP invalid
    0709 = Not an active authentication type
    0710 = Authentication type blocked
    0711 = Biological identify invalid
    0712 = Pattern identify invalid
    0713 = Digital identify invalid
    0714 = Face identify invalid
    0715 = Unknown authentication type
    0716 = Data encryption failure
    0750 = Member channel invalid
    0751 = Data decrypt failed
    0752 = Failed to generate hash
    0753 = Message invalid
    0754 = Member hash invalid
    0755 = JSON parse error
    0758 = Data encryption failure
    0850 = Member channel invalid
    0851 = Data decrypt failed
    0852 = Failed to generate hash
    0853 = Message invalid
    0854 = Member hash invalid
    0855 = JSON parse error
    0856 = Transaction not found
    0857 = Transaction status error
    0858 = Transaction timeout
    0950 = Member channel invalid
    0951 = Data decrypt failed
    0952 = Failed to generate hash
    0953 = JSON parse error
    0954 = Channel invalid
    0955 = iDGateID status error
    0956 = Timeout
    0958 = Data encrypt failed
    0960 = Blocked authentication type
    1000 = Member channel invalid
    1010 = Data encryption failure
    9998 = Need to update security component
    1290 = Verification failure
    2501 = Data decrypt failed
    2502 = Failed to generate hash
    2505 = JSON parse error
    2504 = Member hash invalid
    2503 = Message invalid
    2506 = OTP invalid
    2507 = Request timeout
    2517 = Device hash error
    2558 = Data encryption failure
    2410 = Blocked authentication type
    2456 = Transaction not found
    2408 = Transaction status error
    2458 = Authentication type not set
    2409 = Transaction timeout
    2411 = Biological identify invalid
    2412 = Pattern identify invalid
    2416 = Pattern authentication fails reached limit
    2413 = Digital identify invalid
    2414 = Transaction data doesn't match
    2407 = OTP invalid
    2402 = Failed to generate hash
    2417 = Device hash error
    2454 = Channel invalid
    2400 = Member channel invalid
    2451 = Data decrypt failed
    2453 = JSON parse error
    2404 = Member hash invalid
    2403 = Message invalid
    2310 = Blocked authentication type
    2320 = Invalid authentication type
    2302 = Failed to generate hash
    2358 = Data encryption failure
    2210 = Blocked authentication type
    2254 = Channel invalid
    2253 = JSON parse error
    2251 = Data decrypt failed
    2258 = Data encryption failure
    2203 = Message invalid
    2109 = KeyType not match
    2154 = Channel invalid
    3050 = Member channel invalid
    3052 = Failed to generate hash
    3056 = Transaction not found
    3054 = Channel invalid
    3150 = Member channel invalid
    3156 = Transaction not found
    3256 = Transaction not found
    3257 = Transaction status error
    3260 = OTP invalid
    1496 = FAILED SIGNATURE
    2036 = object null
    2037 = allowedAaids is null
    2054 = DB ERROR
    2061 = object is null
    2025 = Duplicate Key
    2026 = DB ERROR
    2027 = allowedAaids ERROR
    2022 = DB ERROR
    2021 = SERVER DATA ERROR
    2028 = unexpected error
    2041 = SERVER DATA ERROR
    2048 = unexpected error
    2049 = unexpected error
    2001 = parameter error
    2002 = paremeter error
