apiVersion: v1
kind: ConfigMap
metadata:
  name: idenkey-config
data:
  config.properties: |
    i18n_Name = Message
    OTP_Timeout = 300000
    Txn_Timeout = 300000
    LoginTxn_Timeout = 300000
    WSI_API_Key = API_Key
    WSM_API_Key = API_Key
    # FIDO server settings
    # FIDO_SV_IP = http://192.168.0.116:10000/GW/WSM/
    # validation fail limits
    #Digital_Fail_Limit = 3
    #Pattern_Fail_Limit = 3
    ### ---------- iDenkey  -----------###
    # Look out for space at tail when you're setting this config
    ## 1 OnlyOTP = true (\u4E0D\u6AA2\u6838 step 4  \u5167\u7684 OTP and ...  ; default = false)
    ## 2 OnlyFIDO = true (\u4E0D\u6253 step 4  \u5167\u7684 FIDO ; default = false)
    # OnlyOTP = true
    #OnlyFIDO = true
    ##  default enableOTP = true
    # enableOTP = false
    mobilePubKey=3059301306072A8648CE3D020106082A8648CE3D0301070342000403C0A3D74A7BDFC6E8EB0BE90A821A82CB85714E9DEC74062D7E149A4E90D5526A16F52F8919FC99403C978367CEC38E788A7AB0F1E5B8936ED93D5CB01AF93C
    # DbKeyAlias=DbKeyAlias
    RsaKeyAlias=RSAkeyAlias
    ECCkeyAlias=ECCkeyAlias
    SoftRSA = true
    SoftECC= true
    ## default: 300000
    #OTP_Timeout = 300000
    ##  default: 300000
    #Txn_Timeout = 300000
    # validation fail limits
    ##  default: 999
    Digital_Fail_Limit = 999
    Pattern_Fail_Limit = 999
    OTP_Fail_Limit = 12
    # --- Keys settings --- #
    # KeyStorePath \u6C92\u7528\u5230
    #KeyStorePath = D:/RP_iDGate/config/Keys
    HSMPlusMode = Y
    HSMProvider = Cvn
    # HSMProvider = SafeNet
    # RsaKeyAlias = cvn0214a
    #  WHEN HSMProvider is NextKMS
    #BizID = OTP
    # PersoKeyAlias = 01
    ## slot2:TEST2
    # DbKeyAlias = TEST2
    # SetKeyAlias = 05
    ## SafeNet
    HSM_SLOT=2
    HSM_PXD=1234
    # HSMProvider = Cvn
    # PersoKeyAlias = CHBKEY
    # DbKeyAlias = CHBKEY
    # SetKeyAlias = CHBKEY
    PersoKeyAlias = CHBKEY123
    DbKeyAlias = CHBKEY123
    SetKeyAlias = CHBKEY123
    AlwaysCallHSM = N
    # --- ESCP --- #
    MultiPersoKey = N
    # Using Multi Perso Key
    PersoKeyBAlias = 02
    PersoKeyCAlias = 03
    # DecryptUrl and EncryptUrl should write full url with client id 
    EncryptUrl = 
    DecryptUrl =
