apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: discovery-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: discovery
              servicePort: 8761
            path: /*
